version: "3.9"
services:
  compiler-explorer:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "10240:10240"
    volumes:
      - type: bind
        source: ./compiler-explorer
        target: /opt/compiler-explorer

